# Purpose: 
1. Process Google Form Responses from pool play
2. output record info (wins/losses, win ratio/loss ratio, points) for display
3. after pool play is over, output record info for seeding next pool play

### To Do:
1. Modify for day 2
2. input from day 2 round robin
3. output to playoff brackets

### Setup output, get team names

In [91]:
from ReadWriteGDocs import write_gdoc, read_gdoc_range, write_gdoc_cell

num_teams = 45 ### 49 for men, 45 for women ###
master_sheet = "Women's Master" ### Change for men vs women ###

num_gold = 8
num_silver = 6
num_bronze = 6

import pandas as pd
import numpy as np

input_ws = "NY Mini 2019 Score Input - Women's Day 2 (Responses)" ### Change for men vs women ###
output_ws = ["NY Mini 2019 - 2nd Round", "NY Mini 2019 - Day 2 Playoffs"]

c=read_gdoc_range(input_ws, "Form Responses 2", 1,2,1,12)
c=c[0]

# get list of team names from Form Values
results = pd.DataFrame(read_gdoc_range("Form Values Add-on - DO NOT DELETE", "Sheet1", 2, 5 ### 4 for men, 5 for women ###
                                       , 1+num_teams, 5 ### 4 for men, 5 for women ###
                                      ), columns=["Team Name"])

results["Court Number"] = ""
results["Wins"] = 0
results["Losses"] = 0
results["Points"] = 0
results["Pool Ranking"] = 0

# get court numbers from master day 2 - gold
courts = pd.DataFrame(read_gdoc_range(output_ws[0], master_sheet, 4, 2, 9, 10))

# iterate each row
for i in range(1,courts.shape[0]):
    for j in range(0, courts.shape[1]):
        team_name = courts.at[i, j]
        
        if (team_name != "X"):
            team_row = results.loc[results["Team Name"] == team_name]
            results.at[team_row.index, "Court Number"] = courts.at[0, j]
            
# get court numbers from master day 2 - silver
courts = pd.DataFrame(read_gdoc_range(output_ws[0], master_sheet, 4, 8, 9, 10))

# iterate each row
for i in range(1,courts.shape[0]):
    for j in range(0, courts.shape[1]):
        team_name = courts.at[i, j]
        
        if (team_name != "X"):
            team_row = results.loc[results["Team Name"] == team_name]
            results.at[team_row.index, "Court Number"] = courts.at[0, j]
            
            
# get court numbers from master day 2 - bronze

## SKIP FOR MENS BRONZE
courts = pd.DataFrame(read_gdoc_range(output_ws[0], master_sheet, 4, 13, 9, 14))

# iterate each row
for i in range(1,courts.shape[0]):
    for j in range(0, courts.shape[1]):
        team_name = courts.at[i, j]
        
        if (team_name != "X"):
            team_row = results.loc[results["Team Name"] == team_name]
            results.at[team_row.index, "Court Number"] = courts.at[0, j]

# # Drop rows without court number because they are in bronze
# results = results[results["Court Number"] != ""]
# results = results.reset_index(drop=True)

        
# start processing from row 2
# keep track of rows processed using processed

processed = 0
results

,Team Name,Court Number,Wins,Losses,Points,Pool Ranking
0,Boston GHOTANE Black,CT16,0,0,0,0
1,Boston GHOTANE White,CT09,0,0,0,0
2,Boston Hurricanes Black,CT05,0,0,0,0
3,Boston Hurricanes Blue,CT09,0,0,0,0
4,Boston Hurricanes Gold,CT18,0,0,0,0
5,Boston Lady Knights A,CT18,0,0,0,0
6,Boston Lady Knights B,CT05,0,0,0,0
7,DC CYC A,CT11,0,0,0,0
8,DC CYC Black,CT10,0,0,0,0
9,DC CYC Red,CT11,0,0,0,0
10,DC Jin Long,CT16,0,0,0,0
11,DC MVP Bolts,CT18,0,0,0,0
12,Montreal Freemason,CT17,0,0,0,0
13,NJ Fastbelles Jr,CT06,0,0,0,0
14,NJ FUNimania,CT10,0,0,0,0
15,NY BCVA,CT06,0,0,0,0
16,NY CASCSA,CT05,0,0,0,0
17,NY Cranky Pandas,CT06,0,0,0,0
18,NY Freemason A,CT11,0,0,0,0
19,NY Freemason B,CT16,0,0,0,0
20,NY Fresh,CT09,0,0,0,0
21,NY Impact Booming,CT18,0,0,0,0
22,NY Impact Dynamic,CT15,0,0,0,0
23,NY Impact Synergy,CT11,0,0,0,0
24,NY Strangers Earth,CT15,0,0,0,0
25,NY Strangers Fire,CT17,0,0,0,0
26,NY Strangers Wind,CT10,0,0,0,0
27,NY Super mom,CT09,0,0,0,0
28,NY Vikings Rogue,CT10,0,0,0,0
29,NY Vikings Storm,CT15,0,0,0,0
30,Philly CIA,CT15,0,0,0,0
31,Philly CIA Agents,CT09,0,0,0,0
32,Philly CIA Fire,CT06,0,0,0,0
33,Philly Lady Suns,CT05,0,0,0,0
34,Philly Lady Suns Sunsations,CT05,0,0,0,0
35,Toronto Bats,CT11,0,0,0,0
36,Toronto Connex A,CT16,0,0,0,0
37,Toronto Connex B,CT18,0,0,0,0
38,Toronto Connex C,CT16,0,0,0,0
39,Toronto Flying Tigers,CT06,0,0,0,0
40,Toronto Phoenix Blaze,CT17,0,0,0,0
41,Toronto Storm X,CT17,0,0,0,0
42,Toronto Thunder Blue,CT15,0,0,0,0
43,Toronto Thunder Grey,CT10,0,0,0,0
44,Toronto United,CT17,0,0,0,0

### Import new Google Form responses

In [94]:
responses_in = pd.DataFrame(read_gdoc_range(input_ws, "Form Responses 2", processed + 2,2, 200, 12), 
                    columns=c)

responses_in.replace('', np.nan, inplace=True)
responses_in.dropna(inplace=True, how='all')

from math import isnan

print ("Need to process " + str(len(responses_in)) + " games")

Need to process 90 games

### Process each Google Form response - update wins and points for teams

In [95]:
responses_trimmed = responses_in.drop(c[2:5], axis=1)
## Convert to numeric
for i in responses_trimmed.columns:
    responses_trimmed[i] = pd.to_numeric(responses_trimmed[i], downcast='integer', errors='ignore')
    
# iterate through each row of responses_trimmed and see if team name is found

for index,row in responses_trimmed.iterrows():
    team_1_name = row["Team 1 Name"]
    team_2_name = row["Team 2 Name"]
    win1 = 0
    win2 = 0
    loss1 = 0
    loss2 = 0
    points1 = 0
    points2 = 0
    
    # process first set
    score_diff = row["Team 1 Score"] - row["Team 2 Score"]
    points1 += score_diff
    points2 -= score_diff
        
    if (score_diff > 0):
        win1 += 1
        loss2 += 1
    elif (score_diff < 0):
        win2 += 1
        loss1 += 1
    ## if score_diff == 0 then do nothing
        
#     # process second set
#     score_diff = row["Team 1 Score 2"] - row["Team 2 Score 2"]
#     points1 += score_diff
#     points2 -= score_diff
    
#     if (score_diff > 0): # team 1 won
#         win1 += 1
#     elif (score_diff < 0): # team 2 won
#         win2 += 1
#     ## if score_diff == 0 then do nothing
                    
    team_1_row = results.loc[results["Team Name"] == team_1_name]
    results.at[team_1_row.index, "Wins"] = team_1_row["Wins"] + win1
    results.at[team_1_row.index, "Points"] = team_1_row["Points"] + points1
    results.at[team_1_row.index, "Losses"] = team_1_row["Losses"] + loss1
    
    team_2_row = results.loc[results["Team Name"] == team_2_name]
    results.at[team_2_row.index, "Wins"] = team_2_row["Wins"] + win2
    results.at[team_2_row.index, "Points"] = team_2_row["Points"] + points2
    results.at[team_2_row.index, "Losses"] = team_2_row["Losses"] + loss2

    
# add to results: wins and points

    processed = processed + 1
        
print("Number of records processed: " + str(len(responses_trimmed)))

print("Total Processed: " + str(processed))

Number of records processed: 90
Total Processed: 90

### Check results and resolve ties between 2nd and 3rd place (determines gold)

In [96]:
#results.sort_values(by=["Pool Ranking", "Wins", "Points"], ascending=[1,0,0])
results.sort_values(by=["Court Number", "Wins", "Points"], ascending=[1,0,0])

# HEAD TO HEAD
## CT09 - Boston GHOTANE White VS NY Super Mom - GHOTANE
## CT09 - NY Fresh VS Philly CIA Agents - Fresh
## CT10 - Strangers Wind VS Toronto Thunder Grey - Strangers Wind

## CT15 - Strangers Earth VS Viking Storm - Vikings Storm won
## CT15 - Impact Dynamic VS Thunder Blue - Thunder blue

,Team Name,Court Number,Wins,Losses,Points,Pool Ranking
2,Boston Hurricanes Black,CT05,4,1,-1,0
16,NY CASCSA,CT05,3,1,37,0
33,Philly Lady Suns,CT05,2,3,-8,0
6,Boston Lady Knights B,CT05,1,3,-20,0
34,Philly Lady Suns Sunsations,CT05,0,3,-28,0
17,NY Cranky Pandas,CT06,4,0,44,0
15,NY BCVA,CT06,3,1,23,0
32,Philly CIA Fire,CT06,2,2,13,0
39,Toronto Flying Tigers,CT06,1,3,-7,0
13,NJ Fastbelles Jr,CT06,0,4,-73,0
1,Boston GHOTANE White,CT09,3,1,31,0
27,NY Super mom,CT09,3,1,14,0
20,NY Fresh,CT09,2,2,16,0
31,Philly CIA Agents,CT09,2,2,0,0
3,Boston Hurricanes Blue,CT09,0,3,-41,0
8,DC CYC Black,CT10,4,0,31,0
26,NY Strangers Wind,CT10,2,2,18,0
43,Toronto Thunder Grey,CT10,2,2,-19,0
14,NJ FUNimania,CT10,1,3,-10,0
28,NY Vikings Rogue,CT10,1,3,-20,0
7,DC CYC A,CT11,4,0,35,0
35,Toronto Bats,CT11,3,1,18,0
18,NY Freemason A,CT11,1,3,-5,0
9,DC CYC Red,CT11,1,3,-16,0
23,NY Impact Synergy,CT11,1,3,-32,0
30,Philly CIA,CT15,4,0,50,0
24,NY Strangers Earth,CT15,2,2,-9,0
29,NY Vikings Storm,CT15,2,2,-12,0
42,Toronto Thunder Blue,CT15,1,3,-4,0
22,NY Impact Dynamic,CT15,1,3,-25,0
36,Toronto Connex A,CT16,4,0,39,0
10,DC Jin Long,CT16,3,1,18,0
0,Boston GHOTANE Black,CT16,2,2,-6,0
38,Toronto Connex C,CT16,1,3,-5,0
19,NY Freemason B,CT16,0,4,-46,0
41,Toronto Storm X,CT17,4,0,46,0
12,Montreal Freemason,CT17,3,1,20,0
25,NY Strangers Fire,CT17,2,2,-10,0
44,Toronto United,CT17,1,2,-1,0
40,Toronto Phoenix Blaze,CT17,0,5,-55,0
4,Boston Hurricanes Gold,CT18,4,0,27,0
21,NY Impact Booming,CT18,3,1,19,0
37,Toronto Connex B,CT18,2,2,1,0
11,DC MVP Bolts,CT18,1,3,-6,0
5,Boston Lady Knights A,CT18,0,4,-41,0

### Sort results by court number, team name

### Update display for standings

In [85]:
# sort by court number and team name

disp_results = results.sort_values(by=["Court Number", "Team Name"]).reset_index(drop=True)

# update display output - court numbers and team names - one time only
# for i in range(0, len(disp_results)):
#     write_gdoc_cell(disp_results.at[i, "Court Number"], output_ws[0], "ScoreDisp", 5+i, 9)  ## 2 for men, 9 for women
#     write_gdoc_cell(disp_results.at[i, "Team Name"], output_ws[0], "ScoreDisp", 5+i, 10) ## 3 for men, 10 for women
    
# # # update display output - wins and points - keep updating
for i in range(0, len(disp_results)):
    write_gdoc_cell(int(disp_results.at[i, "Wins"]), output_ws[0], "ScoreDisp", 5+i, 11) ## 4 for men, 11 for women
    write_gdoc_cell(int(disp_results.at[i, "Points"]), output_ws[0], "ScoreDisp", 5+i, 12) ## 5 for men, 12 for women

### Sort results by court number, wins, points

### Write team names and records to Gold, Silver, Bronze brackets

# Need to adjust
- Gold: top 2 teams from each pool goes into playoffs (total 8)
- Silver: top 2 teams from each pool goes into playoffs (total 6)
- Bronze: top 3 teams from each pool goed into playofffs (total 6)

In [97]:
# sort by court number, wins, points for seeding
results = results.sort_values(by=["Court Number", "Wins", "Points"], ascending=[1,0,0]).reset_index(drop=True)

# assign pool rankings

for court in results["Court Number"].unique():
    # retrieve pool
    pool = results[results["Court Number"] == court]
    # sort by wins and points
    pool = pool.sort_values(by=["Wins", "Points"], ascending=[0,0]).reset_index(drop=True)
    
    # assign rankings
    for i in range(0, len(pool)):
        results.loc[results["Team Name"] == pool.loc[i, "Team Name"], "Pool Ranking"] = i+1

# do not use chained assignments - [] then []
# results["Pool Ranking"][results["Team Name"] == team["Team Name"]] = 4
# use this instead
# results.loc[results["Team Name"] == team["Team Name"], "Pool Ranking"] = 6

mens_gold_courts = ["CT01", "CT02", "CT03", "CT04"]
womens_gold_courts = ["CT15", "CT16", "CT17", "CT18"]
mens_silver_courts = ["CT12", "CT13", "CT14"]
womens_silver_courts = ["CT09", "CT10", "CT11"]
womens_bronze_courts = ["CT05", "CT06"]

mens_gold = results[results["Court Number"].isin(mens_gold_courts)].reset_index(drop=True)

mens_silver = results[results["Court Number"].isin(mens_silver_courts)].reset_index(drop=True)


womens_gold = results[results["Court Number"].isin(womens_gold_courts)].reset_index(drop=True)


womens_silver = results[results["Court Number"].isin(womens_silver_courts)].reset_index(drop=True)

womens_bronze = results[results["Court Number"].isin(womens_bronze_courts)].reset_index(drop=True)

## write team names and records into brackets for gold, silver, women's bronze

ws = "NY Mini 2019 - Day 2 Playoffs"
# sheets = ["Men's GOLD", "Men's SILVER"] ## Change for womens
# pools = [mens_gold, mens_silver] ## Change for womens

sheets = ["Women's GOLD", "Women's SILVER" "Women's BRONZE"]
pools = [womens_gold, womens_silver, womens_bronze]

for sheet in sheets:
    for pool in pools:
        for i in range(0, len(pool)):
            write_gdoc_cell(pool.at[i, "Team Name"], ws, sheet, i+4, 4)
            write_gdoc_cell(int(pool.at[i, "Pool Ranking"]), ws,sheet, i+4, 3)
            write_gdoc_cell(pool.at[i, "Court Number"], ws, sheet, i+4, 2)
            write_gdoc_cell(int(pool.at[i, "Wins"]), ws, sheet, i+4, 5)
            write_gdoc_cell(int(pool.at[i, "Points"]), ws, sheet, i+4, 6)

KeyboardInterrupt:

In [104]:
womens_gold.loc[results["Team Name"] == "NY Strangers Earth", "Pool Ranking"] = 3
womens_gold.loc[results["Team Name"] == "NY Vikings Storm", "Pool Ranking"] = 4
## CT15 - Strangers Earth VS Viking Storm - Vikings Storm won
## CT15 - Impact Dynamic VS Thunder Blue - Thunder blue
womens_gold.sort_values(by=["Pool Ranking", "Wins", "Points"], ascending=[1,0,0])

                 Team Name Court Number  Wins  Losses  Points  Pool Ranking
0               Philly CIA         CT15     4       0      50             1
10         Toronto Storm X         CT17     4       0      46             1
5         Toronto Connex A         CT16     4       0      39             1
15  Boston Hurricanes Gold         CT18     4       0      27             1
11      Montreal Freemason         CT17     3       1      20             2
16       NY Impact Booming         CT18     3       1      19             2
6              DC Jin Long         CT16     3       1      18             2
1       NY Strangers Earth         CT15     2       2      -9             2
17        Toronto Connex B         CT18     2       2       1             3
7     Boston GHOTANE Black         CT16     2       2      -6             3
12       NY Strangers Fire         CT17     2       2     -10             3
2         NY Vikings Storm         CT15     2       2     -12             3
13          Toronto United         CT17     1       2      -1             4
3     Toronto Thunder Blue         CT15     1       3      -4             4
8         Toronto Connex C         CT16     1       3      -5             4
18            DC MVP Bolts         CT18     1       3      -6             4
4        NY Impact Dynamic         CT15     1       3     -25             5
19   Boston Lady Knights A         CT18     0       4     -41             5
9           NY Freemason B         CT16     0       4     -46             5
14   Toronto Phoenix Blaze         CT17     0       5     -55             5

In [107]:
womens_bronze.sort_values(by=["Pool Ranking", "Wins", "Points"], ascending=[1,0,0])

,Team Name,Court Number,Wins,Losses,Points,Pool Ranking
5,NY Cranky Pandas,CT06,4,0,44,1
0,Boston Hurricanes Black,CT05,4,1,-1,1
1,NY CASCSA,CT05,3,1,37,2
6,NY BCVA,CT06,3,1,23,2
7,Philly CIA Fire,CT06,2,2,13,3
2,Philly Lady Suns,CT05,2,3,-8,3
8,Toronto Flying Tigers,CT06,1,3,-7,4
3,Boston Lady Knights B,CT05,1,3,-20,4
4,Philly Lady Suns Sunsations,CT05,0,3,-28,5
9,NJ Fastbelles Jr,CT06,0,4,-73,5